### ISSUE TITLE
Installing on react-native@0.7.1 breaks app

### ISSUE THREAD

**Issue by dancormier** [superdami/react-native-custom-navigation#1]
I get the following error in the iOS simulator after installing react-native-custom-navigation:

![Simulator](http://i.imgur.com/LzFwcXp.png)

React Packager:

```
React packager ready.

[3:58:32 PM] <START> fs crawl
 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (evalmachine.<anonymous>:1172:11)
    at Object.fs.watch (evalmachine.<anonymous>:1198:11)
    at NodeWatcher.watchdir (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at ReaddirReq.Req.done (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:141:5)
    at ReaddirReq.done (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:88:22)
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
evalmachine.<anonymous>:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EMFILE, too many open files '/Users/dan/.babel.json'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:500:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1099:15)
    at process.save (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/babel-core/lib/babel/api/register/cache.js:36:19)
    at process.emit (events.js:107:17)
    at process.exit (node.js:600:17)
    at process.<anonymous> (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/packager/packager.js:143:11)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at Walker.<anonymous> (/Users/dan/Developer/_projects/choosy/Choosy20150711-2/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
Process terminated. Press <enter> to close the window
```

I've tried both updating the ulimit on my machine and updating react-native inside custom-navigation, but receive the same error.

**Comment by dancormier** [comment]
I'm getting this error in another app, so I think, this is my bad :(
Sorry for bugging you and I look forward to using this component!

**Comment by SuperDami** [comment]
I had met the same issue before, this solution may help

http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os

**Comment by dancormier** [comment]
Great, thank you!
